### ISSUE TITLE
Navigation does not work

### ISSUE THREAD

**Issue by SpecialAgent** [Borisvl/Pdf4Eclipse#5] opened 2011-12-03 11:35 UTC
Hi,

unfort. I can not scroll through my generated PDF document using keyboard, mouse wheel or page navigation in the status bar.

I opened the view by double clicking my document.pdf. There I can see only one page of my PDF... but I can not scroll through the entire PDF. By entering a page number and pressing Enter the view does not navigate to this page... 

I would like to have a "Fit width and show pages continuesly" and "Fit a Single page" like in SumatraPDF... 

Is there any feature that enables this?

Thank you

**Comment by SpecialAgent** [comment] 2011-12-03 11:43
Well... I saw that it is also handled in bug #2

**Comment by Borisvl** [comment] 2011-12-05 16:27
Normally, the navigation via the page up and page down keys or by entering the page number should work. Maybe there is a problem with your pdf file. If you send it to me, I can take a look at it. 
I will add buttons to navigate to the next and previous page.

**Comment by vollkorn** [comment] 2011-12-18 16:52
I have the same issue on Mac OS X Lion. When I scroll to the end of the page, it does not flip over to the next page. Is Mac OS X Lion even supported?

**Comment by dribuschc** [comment] 2011-12-26 16:27
I have the same  problem. I can navigate by entering the page number (took me a while to find that box), but I can't navigate from page to page using the arrow keys or the the mouse wheel or the scroll bar. 
I use the latest eclipse release:

Eclipse IDE for Java Developers
Version: Indigo Service Release 1
Build id: 20110916-0149

on a windows 7 64bit machine

**Comment by vollkorn** [comment] 2011-12-27 17:51
You will see (by looking at the source code) this "feature" is not implemented yet. So its not a bug. :-)

**Comment by Borisvl** [comment] 2012-01-06 12:09
You can use the page up and down keys to change the page. I will add some arrows for page selection soon and also some kind of "fake" continuous scrolling.

**Comment by yuxiangguTemp** [comment] 2012-01-09 19:37
Thanks for the nice plugin. :)

However, same problem in Windows 7. Cannot scroll the entire pdf, only one page.

**Comment by psybers** [comment] 2012-01-16 02:05
Being able to use arrow keys (up/down and left/right) would be very helpful, as would using the scroll wheel.

**Comment by Borisvl** [comment] 2012-03-20 17:29
I checked in some code which should solve this problem. First one can now use the mouse wheel to pseudo continuously scroll through the whole document (thanks MeisterYeti) and furthermore I added some navigation buttons.
I will release a new version soon.

**Closed as completed** 2012-03-21 11:13 UTC
